services:
  - type: web
    name: demo
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx350m -Xss256k
