# Base de datos PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-dapmhlad0e5s739l6gmg-a:5432/pulperiadb
spring.datasource.username=admin
spring.datasource.password=MTbT8vBa4THDdKr6IiJcBF9eCFiwIb6Z
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true