spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/pulperia_landi?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Segura0504.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#para ver las consulas en consola
spring.jpa.show-sql=true 


spring.jpa.hibernate.ddl-auto=update
